### ISSUE TITLE
Missing self. before physical_convert in sensor_data.py

### ISSUE THREAD

**Issue by montavon** [pozyxLabs/Pozyx-Python-library#15]
In sensor_data.py, some classes have an attribute physical_convert. When using this variable, the prefix self., indicating that the class member should be used, is missing and thus leading to an error.
"""
class PositionError(XYZ):
    """
    Container for position error in x, y, z, xy, xz, and yz (in mm).

    Useful in these functions:
        getPositionError
    """
    physical_convert = 1
    byte_size = 12
    data_format = 'hhhhhh'

    def __init__(self, x=0, y=0, z=0, xy=0, xz=0, yz=0):
        """Initializes the PositionError object."""
        XYZ.__init__(self, x, y, z)
        self.xy = xy
        self.xz = xz
        self.yz = yz
        self.data = [x, y, z, xy, xz, yz]

    def load(self, data):
        XYZ.load(self, data[0:3])
        self.xy = data[3] / physical_convert #missing self.
        self.xz = data[4] / physical_convert #missing self.
        self.yz = data[5] / physical_convert #missing self.

    def update_data(self):
        try:
            if self.data != [self.x, self.y, self.z, self.xy, self.xz, self.yz]:
                self.data = [self.x, self.y, self.z, self.xy, self.xz, self.yz]
        except:
            return

    def __str__(self):
        return 'X: {self.x}, Y: {self.y}, Z: {self.z}, XY: {self.xy}, XZ: {self.xz}, YZ: {self.yz}'.format(self=self)
"""

**Comment by laurentva** [comment]
Fixed :)
