### ISSUE TITLE
incorrect return value in  remoteRegWrite

### ISSUE THREAD

**Issue by niamiot** [pozyxLabs/Pozyx-Python-library#16]
Hi, 

I've just pointed that the return vlaue of [remoteRegWrite](https://github.com/pozyxLabs/Pozyx-Python-library/blob/master/pypozyx/core.py#L214)  with the **remote_id** parameter is not correct. It always return 0 even the operation succeed. This can be observed by using e.g.  setUWBChannel (see example below). 
This only appends the 1st time of the call. The second call of the same function returns a correct results 

```python

>>> from pypozyx import *
>>> port = get_serial_ports()[-1][0]
>>> p = PozyxSerial(port)
>>> status = p.setUWBChannel(7,remote_id=0x6065)
>>> status 
0
>>> status = p.setUWBChannel(7,remote_id=0x6065)
1
```

As far as I understand, the issue comes from the [checkForFlag](https://github.com/pozyxLabs/Pozyx-Python-library/blob/master/pypozyx/core.py#L205)  **core.py** .

Indeed, from the 3 status check in [remoteRegWritefunction](remoteRegWrite) , only the last retruns 0:

+ The buffer of the tag is correctly filled ( [status = self.regFunction(POZYX_TX_DATA, send_data, Data([]))](https://github.com/pozyxLabs/Pozyx-Python-library/blob/master/pypozyx/core.py#L232) ; status is 1 ), 
+ The data is correclty send ([status = self.regFunction(POZYX_TX_SEND, params, Data([]))](https://github.com/pozyxLabs/Pozyx-Python-library/blob/master/pypozyx/core.py#L238); status is 1 also).
+ But The [self.checkForFlag(POZYX_INT_STATUS_FUNC, 0.1)](https://github.com/pozyxLabs/Pozyx-Python-library/blob/master/pypozyx/core.py#L241) return 0.

More deeply, 
I suppose this test in [checkForFlag](https://github.com/pozyxLabs/Pozyx-Python-library/blob/master/pypozyx/core.py#L205) is not correct. ( Maybe because interrupt is an integer?)

Related to this, it is not clear what is the value of POZYX_INT_STATUS when  [POZYX_TX_SEND ](https://www.pozyx.io/Documentation/Datasheet/RegisterOverview#POZYX_TX_SEND), is used with REG_WRITE. Data sheet seems to not precise it, and it could be the origin of the issue.

Thank you

**Comment by laurentva** [comment]
Not sure if this is still an issue. For the UWB channel it seems fishy in particular because you're changing UWB settings and the communication back doesn't work on the same UWB settings so fails, leaving 0.
