### ISSUE TITLE
Error in writeTXBufferData 

### ISSUE THREAD

**Issue by UlixDev** [pozyxLabs/Pozyx-Python-library#21]
When I try to write a data buffer into POZYX_TX_DATA I get a POZYX_FAILURE from writeTXBufferData function for buffer size of 27/54/81 bytes!

**Comment by laurentva** [comment]
Can you send me some code to duplicate this issue if still relevant?

**Comment by WouterGordts** [comment]
I'm having the same issue. Everything above 28 bytes fails.

[pozyx_abstraction.txt](https://github.com/pozyxLabs/Pozyx-Python-library/files/2166158/pozyx_abstraction.txt)

Any help is appreciated.

**Comment by WouterGordts** [comment]
Never mind, I figured out why it's happening and how to fix it. The constant MAX_SERIAL is 28 so you have to split up the buffer if you want to create you own function. There is however a new function in the core library called writeTXbufferdata that handles it for you.

**Comment by laurentva** [comment]
Good idea for an example in the documentation rewrite!
