### ISSUE TITLE
getPositionError always returns zeroes

### ISSUE THREAD

**Issue by reinzor** [pozyxLabs/Pozyx-Python-library#40]
```
pos = pypozyx.Coordinates()
pozyx.doPositioning(pos, pypozyx.POZYX_2D)
pos_error = pypozyx.PositionError()
pozyx.getPositionError(pos_error)
pos_error.data
[0, 0, 0, 0, 0, 0]
```

**Comment by ghost** [comment]
When positioning you can choose between two algorithms:
- UWB-only gives you "raw positions", no filtering is done, this is the best algorithm to assess you anchor setup
- Tracking will use current and historic positioning data and sensor data to build a mathematical model that gives more accurate results when the update rate is higher than 1 Hz. It almost always performs better than UWB-only.

The positioning algorithm is chosen using setPositionAlgorithm, both in Arduino as in Python. More information can be found in the Python [docs ](https://www.pozyx.io/Documentation/Datasheet/python#setPositionAlgorithm)and the [register overview](https://www.pozyx.io/Documentation/Datasheet/RegisterOverview#POZYX_POS_ALG). The Arduino library is updated with the tracking algorithm, but the [docs ](https://www.pozyx.io/Documentation/Datasheet/arduino#setPositionAlgorithm) are lagging behind.

The Position Error is only available when using the Tracking algorithm.

**Comment by dennismorits** [comment]
I have the same problem. I writing in Python ROS. I am using the tracking modes. Is there any other condition i have to fullfill.
