### ISSUE TITLE
Invalid character

### ISSUE THREAD

**Issue by AlexisTM** [pozyxLabs/Pozyx-Python-library#42]
SyntaxError: Non-ASCII character '\xc2' in file pypozyx/structures/sensor_data.py on line 156, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

https://github.com/pozyxLabs/Pozyx-Python-library/blob/1a6f3895e024568025bc7dfdd12c3685eea4014f/pypozyx/structures/sensor_data.py#L156

The "°" is not a ASCII character.

This is bugging on Python 2.7.12 (default, Dec  4 2017, 14:50:18) arm version.

**Comment by AlexisTM** [comment]
Adding `# -*- coding: utf-8 -*-` on the second line of each file should solve the issue.

**Comment by laurentva** [comment]
Hey Alexis, didn't know I'd make it Python 2 incompatible. Thanks for pointing this out :)
