### ISSUE TITLE
Changing UWB settings on device failed

### ISSUE THREAD

**Issue by 20chase** [pozyxLabs/Pozyx-Python-library#45]
Hello,

I am a developer using the pozyx. When I use pozyx python api to change the uwb settings, some devices can be changed successfully while some others failed to be changed.  Due to the problem, I cannot localize the multi-tags.

Some information about my setup is following:
* firmware version: 1.1
* 4 anchors
* 2 tags for localization
* 1 tag to get 2 tags' position
* position mode: 2d
* algorithm: uwb_only

in `change_uwb_setting.py`:

> channel=5
> bitrate=2
> prf=1
> plen=0x14
> gain_db=11.5
> devices = [tag_id_1, tag_id_2, anchor_id_1, anchor_id_2, anchor_id_3, anchor_id_4]

in `terminal`:

> settings successfully changed on device tag_id_1
>           and saving settings succeeded
> settings successfully changed on device tag_id_2
>           and saving settings succeeded
> settings successfully changed on device anchor_id_1
>           and saving settings succeeded
> settings successfully changed on device anchor_id_2
>           and saving settings succeeded
> changing uwb setting on device anchor_id_3 failed
> changing uwb setting on device anchor_id_4 failed

So I want to know what should I do? Did I run the script properly? Thanks

**Comment by laurentva** [comment]
Hey 20chase,

This isn't really an issue with the library as far as I'm aware. Can you mail to support@pozyx.io?
