### ISSUE TITLE
Ready To Range Tutorial Returns Only Timeout Errors

### ISSUE THREAD

**Issue by skallaher** [pozyxLabs/Pozyx-Python-library#46]
Tag Firmware Version: 1.1

When running the `ready_to_range.py` tutorial with two tags, the system spits out only `0x12` (POZYX_ERROR_RTIMEOUT1) errors when calling `pozyx.doRanging`. The two tags are on the same UWB settings and are well within range of each other.

Testing has been done on multiple machines and multiple tags with Python version 3.5.3 and a clean clone of this repository. The same tags would run this demo without issues on firmware version 1.0 when they were purchased.

**Comment by laurentva** [comment]
Hey Sean,

Checking your mails, your issues were fixed by upgrading the firmware?
