### ISSUE TITLE
Inconistent operation mode in tutorial 4

### ISSUE THREAD

**Issue by montavon** [pozyxLabs/Pozyx-Python-library#48]
Tutorial 4 defines anchors as `DeviceCoordinates(0x6058, 1, Coordinates(0, 0, 2210))` (and similar). The "1" is, according to the documentation, supposed to represent the operation mode. However, `pypozyx.POZYX_ANCHOR_MODE`is defined as 0. Which one is the correct way of using the library?

**Comment by laurentva** [comment]
Hey Montavon,

You're right, I think they are switched. I'll investigate and fix this in the next release. If you don't mind my curiosity, what are you trying to achieve using the operation mode?

**Comment by Muldec** [comment]
The Operation mode registry (0x22) contains 0 when the jumper sets the device as a Tag and contains 1 when the jumper sets the device as an anchor. 
Therefore @montavon is right : the constant are switched.
Just made a PR with the modification to fix the lib.

**Comment by laurentva** [comment]
Will be fixed going forward when using PozyxConstants.TAG_MODE and PozyxConstants.ANCHOR_MODE starting from 1.2.6. The loose constants will be deprecated in the future in favor of these container classes.
