### ISSUE TITLE
Can not get remote localization to work

### ISSUE THREAD

**Issue by JanMisker** [pozyxLabs/Pozyx-Python-library#50]
I use the tutorials/ready_to_localize.py example. It works great when I have the tag connected to my laptop, I get correct readouts of the position (2D). However I can not get it to work polling the tag remotely. 

I use the same setup, with these changes:
USB cable to an anchor instead of the tag
Tag connected to USB power
Set remote = True and provide the proper remote_id value.
Doing this I get 
`ERROR positioning on ID 0x6978, NO ERROR`

Remote ranging does work, it goes wrong when I try to localize a remote device. Any tips?

**Comment by laurentva** [comment]
As per request in our mail exchange, I will add a latest version check to the tutorials for future use. Thanks again for the suggestion!
