### ISSUE TITLE
get warning "PySerial out of date" even with latest

### ISSUE THREAD

**Issue by GOBish** [pozyxLabs/Pozyx-Python-library#51]
I get a warning when running ready_to_localize.py and oreientation_3D.py that PySerial is out of date, please update to v3.4 if possible. I have checked multiple times and I have the latest PySerial installed. Any ideas?

**Comment by laurentva** [comment]
Hey,

What version of PySerial do you have installed, if I may ask? Is it an overlap between Python 2 and 3 with different packages installed?

You might want to use PozyxSerial(..., suppress_warnings=True) if it's in your way, but you're the first with this issue and I'm not sure what's causing it.

**Comment by laurentva** [comment]
Any update?
