### ISSUE TITLE
dopositioning not working with pypozyx 1.2.1

### ISSUE THREAD

**Issue by dastoqc** [pozyxLabs/Pozyx-Python-library#52]
Tested on 2 different laptop, 2 raspberry pi 3 and 4 raspberry Zero, all connected to a tag through usb. With the latest lib (1.2.1), using python 3.4, 3.5 or 3.6, _doPositioning_ crashes systematically with:
"LOCAL ERROR positioning, ERROR 0x0D: Invalid function parameters for the register function". Tags firmware is 1.2.

It works fine downgrading pypozyx to 1.1.6.

**Comment by laurentva** [comment]
Hey David,

I heard from Ruben that you sorted this out. I've added multi-firmware support to the next release of the Python library, which I'll release soon.

**Comment by dastoqc** [comment]
Hi.

We had to rollback to version 1.1.6 of the python library in order to have it work. I am not sure we can labeled that as "sorted out"... Would be happy to hear about a real fix.

Regards.


David St-Onge, ing. MGP PhD
Ingénieur en arts
davidstonge.info [http://www.davidstonge.info]
Sur 2018-08-27 15:23:32, Laurent <notifications@github.com> a écrit:
Hey David,
I heard from Ruben that you sorted this out. I've added multi-firmware support to the next release of the Python library, which I'll release soon.

**Comment by laurentva** [comment]
Multi-firmware setups are now operational in 1.2.2 release.

**Comment by dastoqc** [comment]
Hi Laurent,

I was wondering: Pozyx way of getting a position from 3 tags (2d) or 4 tags (3D) is based on TWR, right? So you don't need synchronisation between the anchors? Or is it done by the tag when trigerring multiple measurements? Also, do you use only a single-sided TWR, or 3 (or even more) messages to cope with time skewness accurately? From our experiment a dopositioning call takes in average 40ms to complete, does that amke sense with your specifications?


Thank you for your support.

David St-Onge, ing. MGP PhD
Ingénieur en arts
davidstonge.info [http://www.davidstonge.info]
Sur 2018-08-30 11:49:38, Laurent <notifications@github.com> a écrit:
Closed #52 [https://github.com/pozyxLabs/Pozyx-Python-library/issues/52].
