### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by dalynfernandes** [pozyxLabs/Pozyx-Python-library#54]
after running the code i get this error:
ImportError: No module named 'pypozyx.tools'

**Comment by GOBish** [comment]
yes, I get the same thing. It looks like this line was added recently --
from pypozyx.tools.version_check import perform_latest_version_check

if I comment that line out, and set
check_pypozyx_version = False

in the main(), the error gets ignored.

**Comment by laurentva** [comment]
Fixed in the new 1.2.3 release
