### ISSUE TITLE
Remote error

### ISSUE THREAD

**Issue by rievo** [pozyxLabs/Pozyx-Python-library#56]
When I try to localize the remote tag, the returned position is always (0,0,0).
I am using 1.3 Firmware version and the latest python library version, pypozyx-1.2.3 and pyserial-3.4.

It looks like this problem doesn't depend on the number of anchors used to configure the system.

I have tried to change the remote tag but it doesn't change when using another one.
I have also tried to change the base tag with the same results.

We have used the readytolocalize.py from GitHub

Thanks in advance

**Comment by Boubside** [comment]
I think I have the same issue.
Using the ready_to_localize.py example from master to localize a remote tag, the doPositionning() method systematically send an error :
```
ERROR positioning on ID 0x6e23, ERROR 0x0D: Invalid function parameters for the register function
```

0x6e23 is the idea of the tag i want to localize (remote).
I'm using the master branch on a Raspberry pi4 model B with 4 anchors and one remote.

Here is the full output of the example file:
```
------------POZYX POSITIONING V1.3.0 -------------

- System will manually configure tag

- System will auto start positioning

Device information for device 0x6f34
	- Firmware version 2.0
Device information for device 0x6e23
	- Firmware version 1.1

------------POZYX POSITIONING V1.3.0 -------------

List size: 4
Calibration result:
Anchors found: 4
('Anchor IDs: ', <pypozyx.structures.device.DeviceList object at 0xb66e97d0>)
ANCHOR, 0x6f4e, X: -440, Y: 140, Z: 610
ANCHOR, 0x6f34, X: -440, Y: -140, Z: 685
ANCHOR, 0x6f1c, X: 300, Y: -230, Z: 160
ANCHOR, 0x0c52, X: 300, Y: 230, Z: 160
ERROR positioning on ID 0x6e23, ERROR 0x0D: Invalid function parameters for the register function
ERROR positioning on ID 0x6e23, ERROR 0x0D: Invalid function parameters for the register function
...
```

The only modifications I did was changing the anchors positions and ID, setting use_precessing to false, and remote to True.

**Comment by laurentva** [comment]
@Boubside is this still relevant for you?
