### ISSUE TITLE
PozyxSerial, PozyxConnectionError: wrong or busy serial port

### ISSUE THREAD

**Issue by MaxMMadsen** [pozyxLabs/Pozyx-Python-library#58]
Hello,

When I have stopped the python script to make some changes, the port is busy when i run the script again. I have to unplug and plug the tag to be able to run again?

Could you add some routine to PozyxSerial, that tries to close/restart the port? Or am i missing something?

**Comment by laurentva** [comment]
Hey Max,

How did you stop the Python script? From my experience, stopping it with something like Ctrl+D or Ctrl+Z has this effect, but stopping it with Ctrl+C does not.

Kind regards,

**Comment by MaxMMadsen** [comment]
Hi,

I use the Spyder (python 3.6) IDE and Ctrl+C for stopping .

I have found that waiting for a little while solves the issue (4-5 seconds) 😊

Best regards, Max
________________________________
Fra: Laurent <notifications@github.com>
Sendt: 14. december 2018 15:36
Til: pozyxLabs/Pozyx-Python-library
Cc: MaxMMadsen; Author
Emne: Re: [pozyxLabs/Pozyx-Python-library] PozyxSerial, PozyxConnectionError: wrong or busy serial port (#58)


Hey Max,

How did you stop the Python script? From my experience, stopping it with something like Ctrl+D or Ctrl+Z has this effect, but stopping it with Ctrl+C does not.

Kind regards,

**Comment by laurentva** [comment]
Hey Max,

Okay! It sounds rather funky though.
