### ISSUE TITLE
Bug #2 in setSelectionOfAnchors

### ISSUE THREAD

**Issue by UlixDev** [pozyxLabs/Pozyx-Python-library#6]
When I execute the snippet of code
mode = SingleRegister(POZYX_ANCHOR_SEL_MANUAL)
n = SingleRegister(how_many)
tag.tag.setSelectionOfAnchors(mode, n)

The following traceback pops out
raceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/osboxes/prj/dfw/Pozyx_scripts/meanTAGPositioning.py", line 25, in TAGInit
    tag.tag.setSelectionOfAnchors(mode, n)
  File "/usr/local/lib/python2.7/dist-packages/pypozyx/lib.py", line 1171, in setSelectionOfAnchors
    **0] == POZYX_ANCHOR_SEL_AUTO, 'setSelectionOfAnchors: wrong mode'
AssertionError: setSelectionOfAnchors: wrong mode**

**It seems that the assert statement be wrong: specifically the or should be changed in and**  

The bug appears only in python2.7

**Comment by laurentva** [comment]
This was also related to issue #9, fixed.
