### ISSUE TITLE
Error writing to a register through the I2C bus

### ISSUE THREAD

**Issue by Muldec** [pozyxLabs/Pozyx-Python-library#62]
When doing constant positioning through doPositioningWithData, the following error occurs randomly :
 
> ERROR 0x01: Error writing to a register through the I2C bus

The positioning could work for a long period before returning this error or could run for a bried period. Nothing seems related to the occurence of it.

When this error occurs, no further positioning request works. All ends up with this error. I need to restart the tag to reenable the positioning.

**Comment by AndreasAntener** [comment]
I enouter the same problem. Was this resolved, or is there a known issue that causes this?

**Comment by AndreasAntener** [comment]
This problem disappears for me if the subsequent doPosition call is delayed (e.g. for 0.2s) after it returned an error previously.

**Comment by laurentva** [comment]
Closing this issue and we'll follow this up over mail as well, this is a firmware issue.
