### ISSUE TITLE
maximum frequency for ranging measurements

### ISSUE THREAD

**Issue by neorobo** [pozyxLabs/Pozyx-Python-library#64]
For my application I'm interested in using only the range measurement from one anchor and one tag, and so far I've noticed a maximum of ~18 Hz. I've tried both RANGE_PROTOCOL_PRECISION and RANGE_PROTOCOL_FAST options.

Is this the expected data rate? It's probably fine for my application but I just want to make sure things are working as expected. The website only seems to document positioning datarates which are reported to be up to 60 Hz divided by number of tags.

I'm currently on firmware 1.1.

**Comment by laurentva** [comment]
Hey @neorobo 

My apologies for the late reply. Could I kindly ask you to mail to support@pozyx.io if you have other issues that aren't really related to the library in itself?

Are you using the ready to range script? If so, you can remove the whole "led changing code" out of it to see a noticeable increase in update rate.

You're also using the default UWB settings. Depending on the maximum range you want your setup to be able to handle, you can increase the update rate a lot by using faster settings. 

You can find the UWB configurator tutorial, with some explanation for each setting, here: https://www.pozyx.io/documentation/creator/arduino/configuration-of-the-uwb-parameters.

You can also easily use our cloud software to configure the UWB settings of all of your devices.

Kind regards,
Laurent
