### ISSUE TITLE
Off-board positioning

### ISSUE THREAD

**Issue by dwiel** [pozyxLabs/Pozyx-Python-library#68]
The latest version (2.0.0) of the Creator Controller claims to add a feature called "off-board positioning".

> Added off-board positioning, where positions are calculated on the computer instead of the Pozyx. This can improve update rate and z accuracy
https://www.pozyx.io/documentation/pozyx-creator-controller

Is this feature available in the API?

**Comment by Willowblade** [comment]
Hey Zach, 

Unfortunately no, the creator controller uses the library to interface with the Pozyx and combines the range data with our proprietary algorithms. The idea would be to over time improve the on-board positioning on the tag further using the much faster development cycle of the off-board algorithms, which are also used in our enterprise kit.

**Comment by laurentva** [comment]
Hey Zach,

Unfortunately no, the creator controller uses the library to interface with the Pozyx and combines the range data with our proprietary algorithms. The idea would be to over time improve the on-board positioning on the tag further using the much faster development cycle of the off-board algorithms, which are also used in our enterprise kit.
