### ISSUE TITLE
How to connect remotely ?

### ISSUE THREAD

**Issue by BenjaminLaschkar** [pozyxLabs/Pozyx-Python-library#75]
Hi,

My pozyx is working great in the app.

I am now tring to access to my pozyx data in python so I used the script that you provided which did great when used with a cable.

But now I want to access to the data in remote so from the doc/code I am adding my remote_id and I change for remote = True.

    remote_id = 0x692d                
    remote = True 

But the code ReadyToLocalize need a pozyx variable and it seems that the only way to have one is with the following : 

    pozyx = PozyxSerial(serial_port)

I tryed to put the serial_port of one anchor connected to my computer (like described in issue #50) But I have this message : 
"pypozyx.core.PozyxConnectionError: Connected to device, but couldn't read serial data. Is it a Pozyx?"

Can you help me connecting remotely and provide more info about remote connection ?  I am surely missing something :) 

Benjamin

**Comment by laurentva** [comment]
Hey Benjamin,

You can't connect to a tag remotely, you need to have a master tag connected to your computer which then can query remote tags over UWB. But you always need a Pozyx device connected to your computer.
